### ISSUE TITLE
Some Placeholders in Console log are not replaced correctly

### ISSUE THREAD

**Issue by Morphyum** [Morphyum/PersistentMap#15]
[Picture](https://cdn.discordapp.com/attachments/487183354639286282/505772396578340890/unknown.png)
See picture

**Comment by IceRaptor** [comment]
Added interpolation symbol to string, which corrects the issue. See https://github.com/Morphyum/PersistentMap/commit/4fc20668b223110f5d53b0ce63ea1d9486496e08
